libraryapp/urls.py
from django.urls import path  #django package
from .views import *
from django.urls import include, path
from django.urls import path

#This file will define all of the URLs that your library application will respond to.

app_name = "libraryapp"  #name of the app. this is there so we can have multiple apps.  Like account.

urlpatterns = [
    path('', home, name='home'),
    path('books/', book_list, name='books'),      #first is taco for direction, view, name for reverse
    path('librarians/', librarian_list, name='librarians'),
    path('libraries/', library_list, name='libraries'),
    path('accounts/', include('django.contrib.auth.urls')),  #for built in login and logout
    path('logout/', logout_user, name='logout'),  #logout path
    path('book/form', book_form, name='book_form'),
    path('library/form', library_form, name='library_form'),
    path('books/<int:book_id>/', book_details, name='book'),  #The <int:book_id> part of that URL pattern is used to capture any integer that is the route parameter, and stores that number in the book_id variable.
    path('books/<int:book_id>/', book_details, name='book'),
    path('libraries/<int:library_id>/', library_details, name='library'),
]

libraryproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls import path
from libraryapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libraryapp.urls')),
]

libraryapp/models/book.py
from django.db import models #This import is needed for Python classes that are modeling a database table
from .library import Library  ## import for the foreign keys
from .librarian import Librarian  ## import for the foreign keys


class Book (models.Model):

    title = models.CharField(max_length=50)  ## properties for the class
    ISBN = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    year_published = models.CharField(max_length=50)
    location = models.ForeignKey(Library, on_delete=models.CASCADE)  ## foreign keys
    librarian = models.ForeignKey(Librarian, on_delete=models.CASCADE)  ## foreign keys

    class Meta:
        verbose_name = ("Book")
        verbose_name_plural = ("Books")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Book_detail", kwargs={"pk": self.pk})

libraryapp/models/librarian.py
from django.db import models  #This import is needed for Python classes that are modeling a database table
from django.contrib.auth.models import User  #django user package
from django.db.models.signals import post_save   #django user package
from django.dispatch import receiver   #django user package
from .library import Library


class Librarian(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.ForeignKey(
        Library, related_name="librarians",
        null=True, # Makes column nullable in DB
        blank=True, # Allows blank value on objects
        on_delete=models.CASCADE)


# These receiver hooks allow you to continue to
# work with the `User` class in your Python code.


# Every time a `User` is created, a matching `Librarian`
# object will be created and attached as a one-to-one
# property
@receiver(post_save, sender=User)
def create_librarian(sender, instance, created, **kwargs):
    if created:
        Librarian.objects.create(user=instance)

# Every time a `User` is saved, its matching `Librarian`
# object will be saved.
@receiver(post_save, sender=User)
def save_librarian(sender, instance, **kwargs):
    instance.librarian.save()

libraryapp/models/library.py
from django.db import models

class Library(models.Model):

    title = models.CharField(max_length=50)
    address = models.CharField(max_length=50)

    class Meta:
        verbose_name = ("library")
        verbose_name_plural = ("libraries")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("library_detail", kwargs={"pk": self.pk})

libraryapp/models/modelfactory.py
import sqlite3

# Higher order function to create instances of models
# when performing single table queries
def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

libraryapp/views.py
from django.shortcuts import render

# Create your views here.

libraryapp/views/connection.py
class Connection:
    db_path = "/Users/datduu.../workspace/python/library-management/libraryproject/db.sqlite3"



#This allows any view to import the path to the database so each can connect to it and query data.

    

libraryapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

libraryapp/templates/books/detail.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>{{ book.title }}</h1>
    <h2>By {{ book.author }}</h2>

    <div>Published in {{ book.year_published }}</div>
    <div>ISBN: {{ book.ISBN }}</div>
  </body>
  <form action="{% url 'libraryapp:book' book.id %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="actual_method" value="DELETE">
    <button>Delete</button>
</form>
</html>

libraryapp/templates/books/form.html
{% comment %} #creates a form to allow users to add a book. {% endcomment %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bangazon</title>
  </head>
  <body>
    <h1>Inventory Book</h1>


    <form action="{% url 'libraryapp:books' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="title">Title: </label>
          <input id="title" type="text" name="title">
      </fieldset>
      <fieldset>
          <label for="author">Author: </label>
          <input id="author" type="text" name="author">
      </fieldset>
      <fieldset>
          <label for="year_published">Year of publication: </label>
          <input id="year_published" type="number" name="year_published">
      </fieldset>
      <fieldset>
          <label for="isbn">ISBN: </label>
          <input id="isbn" type="text" name="isbn">
      </fieldset>
      <fieldset>
          <label for="location">Library: </label>
          <select id="location" type="text" name="location">
                {% for library in all_libraries %}
                    <option value="{{ library.id }}">{{ library.title }}</option>
                {% endfor %}
          </select>
      </fieldset>

      <input type="submit" value="Add It" />
    </form>
  </body>
</html>

libraryapp/templates/books/list.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>Books</h1>

    <ol>
    {% for book in all_books %}
        <li>
          <a href="{% url 'libraryapp:book' book.id %}"> {{ book.title }} </a>
          by {{book.author}} published in {{book.year_published}}
        </li>
        
        
        {% comment %} <li>
            {{ book.title }}
            by {{book.author}}
            published in {{book.year_published}}
        </li> {% endcomment %}
    {% endfor %}
    </ol>
  </body>
</html>


{% comment %} This what appears when the /books URL is requested {% endcomment %}

libraryapp/templates/home.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Nashville Library Management System</title>
</head>

<body>

    <h1>Welcome to the Nashville Library Management System</h1>

</body>

</html>

libraryapp/templates/librarians/list.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>Librarians</h1>

    <ol>
    {% for librarian in all_librarians %}
        <li>{{ librarian.first_name }} {{ librarian.last_name }}</li>
    {% endfor %}
    </ol>
  </body>
</html>

libraryapp/templates/libraries/detail.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>{{ library.title }}</h1>
    <h2>By {{ library.address }}</h2>
  </body>
</html>

libraryapp/templates/libraries/form.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bangazon</title>
  </head>
  <body>
    <h1>Inventory Library</h1>


    <form action="{% url 'libraryapp:libraries' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="title">Title: </label>
          <input id="title" type="text" name="title">
      </fieldset>
      <fieldset>
          <label for="address">Address: </label>
          <input id="address" type="text" name="address">
      </fieldset>
      <input type="submit" value="Add It" />
    </form>
  </body>
</html>

libraryapp/templates/libraries/list.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>Libraries</h1>

    <ol>
    {% for library in all_libraries %}
        <li>{{ library.title }} {{ library.address }}</li>
        <a href="{% url 'libraryapp:library' library.id %}"> {{ library.address }} </a>
    {% endfor %} 
    </ol>
  </body>
</html>